version: '3.8'
 services:
   web:
 	build: ./app
 	ports:
   	- "5000:5000"
 	depends_on:
   	- db
   db:
 	build: ./db
 	environment:
   	MYSQL_ROOT_PASSWORD: root
   	MYSQL_DATABASE: imc_db
 	ports:
   	- "3306:3306"